### ISSUE TITLE
Clang upgrades

### ISSUE THREAD

**Issue by TheRustifyer** [zerodaycode/Zork#127]
## Feature Request

This issue is a tracking issue for sub-tasks related with the newest versions of `Clang` and the `LLVM` project

### Tasks

- [ ] `-fmodule-file` to the new format (#123)
- [ ] `import std` and `import std.compat` (#124)
- [ ] `two-phase` compilation model for `module interfaces` (#125)
- [ ] gather the metadata of the compiler in the cache (#126)
